name: Punisher
main: me.clannoobz.punisher.punishermain
version: 0.1
author:
#***********
#*clannoobz*
#***********
description: Punishes people
commands:
  punisher:
    description: Tells if loaded
    usage: 