name: Punisher
main: me.clannoobz.punisher.punishermain
version: 0.1
author:
#***********
#*clannoobz*
#***********
description: Punishes people if they do something wrong; griefing, breaking a rule, etc.
commands:
  punisher:
    description: Tells version loaded.
    usage: