name: Punisher
main: me.clannoobz.punisher.punishermain
version: 0.1
author:
#***********
#*clannoobz*
#***********
description: >
Punishes people if they do something wrong; griefing, breaking a rule, etc.
Also notifies when a punishment is to happen.
commands:
  punisher:
    description: Tells version loaded.
    usage: >
    /punisher
    /punisher reload